거래내역 삭제 구현
boostcamp-2020/Project16-A-Account-Book pull request #162
Opened 2020-12-08 16:00 UTC by yejineee

![2020-12-09 00 25 00](https://user-images.githubusercontent.com/43772082/101507274-bb5b7c00-39b9-11eb-8c94-1a2d3698b79d.gif)
## 변경사항 
- 거래내역 수정 페이지에서 쓰레기통 버튼을 클릭하면, 거래내역이 삭제되도록 하였습니다.
- 거래내역 리스트 페이지에서 삭제된 것은 제외시키고 가져오도록 하였습니다.

## 체크리스트

## Linked Issues

## 멘토님들
@boostcamp-2020/accountbook_mentor

2020-12-08 16:33 UTC, rolled-potatoes approved these changes
API 까지 좋습니다 ~

2020-12-09 00:10 UTC, pkiop requested changes
올려주신 gif에서 트렌젝션 클릭했는데 클릭한 트렌젝션의 정보가 수정페이지로 안들어가는 것 같아요!

2020-12-09 00:50 UTC, yejineee commented
> 올려주신 gif에서 트렌젝션 클릭했는데 클릭한 트렌젝션의 정보가 수정페이지로 안들어가는 것 같아요!

수정페이지로 들어가지는건 맞는데, 서버로부터 데이터를 가져오는게 느려서 ...ㅠㅠㅠ 반영되기전에 찍힌 것 같습니다.
ref타입의 한계가 아닐까ㅠㅠ

2020-12-09 01:21 UTC, pkiop approved these changes

2020-12-09 01:50 UTC, merged