카테고리, 결제수단 조회 API 작성
boostcamp-2020/Project16-A-Account-Book pull request #94
Opened 2020-12-01 08:47 UTC by rolled-potatoes

## 변경사항 
```js
router.use('/category', categoryRouter.routes());
router.use('/method', methodRouter.routes());
```
리스트를 가져오는 API를 라이팅하여 가져올 수 있게 하였습니다.
파라미터로는 accoumtObjId를 넣어주야 한다. 

## 체크리스트

- [x]  accountObjId를 파라미터로 받는다
- [x] accountObjId를 파라미터로 받는다
- [x] 분류된 결과 값이 반환된다.

## Linked Issues
closes #92 #93 
## 멘토님들
@boostcamp-2020/accountbook_mentor

2020-12-01 08:59 UTC, yejineee commented on be/src/controllers/category/index.ts
> +  const {accountObjId} = ctx.params;
승환님 뭔가 eslint, prettier가 적용이 안되는 것 같네용..?

2020-12-01 09:01 UTC, yejineee commented on be/src/services/category/index.ts
> +  const categorisedType = res?.categories?.reduce((acc :any ,cur:any)=>{
categorizedType이 맞지 않을까 싶습니당...!

2020-12-01 10:22 UTC, rolled-potatoes commented on be/src/controllers/category/index.ts
> +  const {accountObjId} = ctx.params;
수정했습니다.

2020-12-01 12:28 UTC, pkiop commented on be/src/models/database.ts
> +import {AccountModel} from './account';
린트 적용 안된 파일이 더 있는 듯 합니다~

2020-12-01 12:29 UTC, pkiop commented on be/src/routers/api/method/index.ts
> +import methodController from '../../../controllers/method';
alias로 지정하면 더 깔끔할 것 같아요!

2020-12-01 12:40 UTC, pkiop commented on be/src/models/transaction/index.ts
> +export interface ITransaction {
interface앞에 I로 네이밍 하니까 훨씬 좋네요! 제가 짠 것도 수정해야겠습니다

2020-12-01 12:44 UTC, pkiop requested changes
be/src/controllers/method/index.ts나 be/src/models/database.ts등 린트 적용 안된 파일 수정해주세요~! vscode에서 저장할 때 적용이 안되면 npx eslint --fix 이렇게 터미널에서 실행하면 적용되더라구요

2020-12-01 12:59 UTC, rolled-potatoes commented on be/src/routers/api/method/index.ts
> +import methodController from '../../../controllers/method';
잊고 있었는데 수정하겠습니다 ~

2020-12-01 14:17 UTC, rolled-potatoes commented
> be/src/controllers/method/index.ts나 be/src/models/database.ts등 린트 적용 안된 파일 수정해주세요~! vscode에서 저장할 때 적용이 안되면 npx eslint --fix 이렇게 터미널에서 실행하면 적용되더라구요

찾아보니 윈도우 wsl 켤때 eslint 적용 안되더군요 ... 
지금 작업하던거 마무리하고 적용하겠습니다.

2020-12-01 23:10 UTC, pkiop approved these changes

2020-12-02 03:59 UTC, yejineee approved these changes
수고하셨습니당!!

2020-12-02 09:22 UTC, dbstjrwnekd approved these changes

2020-12-02 09:54 UTC, yejineee commented on be/src/routers/api/index.ts
> +router.use('/method', methodRouter.routes());
/categories, /methods 로 수정해야 할 것 같아요! API 설계에 맞춰야 할 것 같습니다

2020-12-03 04:58 UTC, merged